apiVersion: v1
kind: Secret
metadata:
  name: logitrack-secret
  namespace: logitrack
  labels:
    app.kubernetes.io/name: logitrack
    app.kubernetes.io/component: backend
type: Opaque
data:
  DB_USER: <BASE64_ENCODED_HERE>
  DB_PASSWORD: <BASE64_ENCODED_HERE>
  SECRET_KEY: <BASE64_ENCODED_HERE>