apiVersion: v1
kind: Service
metadata:
  name: logitrack
  namespace: logitrack
  labels:
    app.kubernetes.io/name: logitrack
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: logitrack
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 80
      targetPort: 8000
